name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main   # triggers deployment on main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v0.23.0
      with:
        hugo-version: '0.115.2'

    - name: Build Hugo site
      working-directory: web-v2
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: web-v2/public

